version: '3.5'

services:
  dev_server:
    build: ./
    command: sh -c "yarn install && yarn start:dev"
    env_file: .env.development
    ports:
      - 3000:3000
    working_dir: /app/server
    volumes: 
      - ./:/app/server